#!/bin/bash
#blow box coordinates by coarse factor and change box size if requested
echo "Prepare to change box coordinates (EMAN2 format) in current folder: [$PWD]"
echo "Make sure that box files and original micrographs have same numbering!"
if ls *.box &> /dev/null
then :
else
echo "No box files found! Exiting.." && exit 1
fi
mkdir new_boxes
Blow=1
NewBox=80
Base="img"
mic=2048
pix=2
echo -n "Coarse factor (1,2,4,6 etc): [1] "
read Blow
echo -n "New box size: [80] "
read NewBox
echo -n "Basename of output box files: [img] "
read BaSe
echo -n "Size of blowed micrographs (e.g. 1024,2048,4096): [2048] "
read mic
echo -n "Remove all boxes closer than X pixels to the borders: [2] "
read pix
B0=$pix
BXY=$((mic-pix))
ex=`ls *.box | tail -1`
OldBox=`cat $ex | awk 'NR==1 {print $3;}'`
NewHalfBox=$(($NewBox/2))
echo -e "Starting calculation of new box coordinates.." | tee boxing.log
for i in `ls *.box`
do
Num=`echo $i | sed 's/[^0-9]*//g'`
echo -n "Checking $i..." | tee -a boxing.log
count=0
while read -r line
do
Xold=`echo ${line} | awk '{print $1}'`
Yold=`echo ${line} | awk '{print $2}'`
Xnew=$((Xold*Blow))
Ynew=$((Yold*Blow))
X1=$((Xnew-NewHalfBox))
X2=$((Xnew+NewHalfBox))
Y1=$((Ynew-NewHalfBox))
Y2=$((Ynew+NewHalfBox))
if [ "$X1" -gt "$B0" ] && [ "$Y1" -gt "$B0" ] && [ "$X2" -lt "$BXY" ] && [ "$Y2" -lt "$BXY" ];then
printf "%-8d%-6d%6d%8d\n" $Xnew $Ynew $NewBox $NewBox >> new_boxes/${BaSe}${Num}.box
else
((count++))
fi
done < $i
( [ $count -eq "0" ] && echo "" ) || ( echo "${count} particles has been removed!" | tee -a boxing.log )
done
echo "Done! Your new box files are new_boxes/${BaSe}*.box. Check boxing.log file!"
